### PR TITLE
V1.2b yf (remove dependencies)

### LINKED ISSUE #106: Remove Dependency from AB3 Model Package

### PR DESCRIPTION
**Pull request by YuFeng0930**
Delete all AB3 things in model.

Delete seedu.address.model.util.SampleDataUtil.java without adding a new one for sochedule now.

### CODE REVIEW

**Review by ljhgabe — APPROVED** [review]
LGTM

**Review by litone01 — COMMENTED** [review]
Can these changes can pass all the current unit tests?

**Comment by YuFeng0930** [comment]
> Can these changes can pass all the current unit tests?

It didn't pass, since the unit tests now are mostly old ones that haven't been updated yet.

**Review by SoulUseless — APPROVED** [review]
LGTM

**Pull request merged**
